# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecurityApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecurityApp
pod 'IQKeyboardManagerSwift'
#pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.5.0'
#pod 'SideMenu', '~> 4.0.0'
#pod 'DropDown', '2.3.2'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'BadgeSwift'
#pod 'FSCalendar'


  target 'SecurityAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecurityAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
